### ISSUE TITLE
How about we contribute to together.

### ISSUE THREAD

**Issue by Itsfoss0** [grand-rick001/C-plus-plus#1]
Hi there @grand-rick001, 
Trust this finds you well. 
I was thinking, how about we contribute to this repository together? ( Just a thought) 
Where we can update the progress in learning CPP, the resources and challenges encountered and how each solved them here. 
Crowd Sourced learning, that what I mean.
Regards,
Ebenezer R.

**Comment by kabugatti** [comment]
I'm okay with that idea.

**Comment by Itsfoss0** [comment]
Awesome,
I was thinking a curated a curated list of resources, challenges and concepts in a README file like I did in one of my projects [Here](https://github.com/Itsfoss0/alx-system_engineering-devops) ^_^ I'll Open a PR in two days then and let you have a look.
Regards,
Ebenezer R.

**Comment by kabugatti** [comment]
That would be great, I'll be waiting for it then we'll sort out the details of the structure of the contributions, that'll go hand in hand with our CPP learning journey.
